services:

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      - DISABLE_IPV6=true
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  status:
    image: dockurr/statping
    privileged: true
    ports:
      - '8080:8080'
    volumes:
      - ./status:/app
    cap_add:
      - NET_RAW
    stop_grace_period: 1m
